language: java
sudo: required
cache: 
  directories:
    - $HOME/.m2
    - node_modules 
    - bower_components
jdk:
  - oraclejdk8
script: 
  - cd desapp-grupoe-backend 
  - mvn clean install -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8
  - cd ../desapp-grupoe-frontend
  - curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash - && sudo apt-get install -y nodejs
  - sudo npm install -g grunt-cli
  - sudo npm install -g bower
  - sudo npm install grunt
  #- npm install
  #- bower install
  - sudo grunt 
  - cd ../desapp-grupoe-backend
  
deploy:
  skip_cleanup: true
  provider: heroku
  api_key: d75c7509-1a26-4283-ba25-3e59df710b8f
  app: adondevamos
