language: java
sudo: required
cache: 
  directories:
    - $HOME/.m2
    - node_modules # NPM packages
jdk:
  - oraclejdk8
script: 
  - cd desapp-grupoe-backend 
  - mvn clean install -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8
  - cd ..
  - curl -sL https://deb.nodesource.com/setup_4.x | sudo bash -
  - sudo apt-get install -y nodejs npm
  - cd desapp-grupoe-frontend
  - sudo npm install grunt-cli bower
  - sudo npm install
  - ls
  - sudo grunt 
deploy:
  provider: heroku
  api_key: d75c7509-1a26-4283-ba25-3e59df710b8f
  app: adondevamos
